version: '3.2'

services:

  server:
    image: 'macthegif/jenkins-docker:1.1'
    ports:
      - "8080"
      - "50000"
    volumes:
      - "home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
 
    networks:
      - default

volumes:
  home:

networks:
  default:
    driver: overlay
    attachable: true

